### ISSUE TITLE
Can't add new styles in python2

### ISSUE THREAD

**Issue by moham96** [tkarabela/pysubs2#12]
Hi,
When adding a new style to the subtitles I get the following error:
```
Traceback (most recent call last):
  File "colorset.py", line 20, in <module>
    subs1.save(foutput,format_='ass')
  File "/home/mohammad/.local/lib/python2.7/site-packages/pysubs2/ssafile.py", line 190, in save
    self.to_file(fp, format_, fps=fps, **kwargs)
  File "/home/mohammad/.local/lib/python2.7/site-packages/pysubs2/ssafile.py", line 222, in to_file
    impl.to_file(self, fp, format_, fps=fps, **kwargs)
  File "/home/mohammad/.local/lib/python2.7/site-packages/pysubs2/substation.py", line 253, in to_file
    fields = [field_to_string(f, getattr(ev, f)) for f in EVENT_FIELDS[format_]]
  File "/home/mohammad/.local/lib/python2.7/site-packages/pysubs2/substation.py", line 242, in field_to_string
    raise TypeError("Unexpected type when writing a SubStation field")
TypeError: Unexpected type when writing a SubStation field

```

If I run the same code in python3 it runs fine but if i run it under python2 i get the error,
I'm trying to use pysubs2 in kodi which currently only support python2.
The code I used
```
import pysubs2
import chardet

finput='en.srt'
foutput='en.ass'
with open(finput,'rb') as fi:
	rawdata = fi.read()
	encoding = chardet.detect(rawdata)['encoding']
fi.close()

subs1 = pysubs2.load(finput)
top_style = pysubs2.SSAStyle()
top_style.alignment=8
subs1.styles['top-style'] = top_style
for line in subs1:
	line.style='top-style'
subs1.save(foutput,format_='ass')
```

**Comment by moham96** [comment]
I think this project is not maintained anymore :(
I was able to find the problem so I'm leaving this for anyone who might encounter the same problem or might want to fix the library.
The problem is in the field_to_string function
https://github.com/tkarabela/pysubs2/blob/ddd0c2e79bcf4fcb497feaf8afc22c5d70334aa5/pysubs2/substation.py#L225-L242
At line 234 It checks whether the field ('style' in our case ) is of type text, but it does this differently in python3 and python2, In Py3 it compares it to 'str' type while in Py2 it compares it to Unicode type.
This can probably be fixed in the library but I didn't bother changing it.
So I just changed the input to unicode like so:
```
import pysubs2
import chardet

finput='en.srt'
foutput='en.ass'
with open(finput,'rb') as fi:
	rawdata = fi.read()
	encoding = chardet.detect(rawdata)['encoding']
fi.close()

subs1 = pysubs2.load(finput)
top_style = pysubs2.SSAStyle()
top_style.alignment=8
subs1.styles['top-style'] = top_style
subs1[0].style= u'top-style'
for line in subs1:
	line.style='top-style'
subs1.save(foutput,format_='ass')

```

**Comment by tkarabela** [comment]
I don't have much time to develop this library anymore, but every now and then I manage to release a new version, so it's not quite dead :)

The best way to use pysubs2 is from Python 3 or Python 2 with `from __future__ import unicode_literals`. I was able to fix your particular issue, so your original code now works as expected with Python 2.7 and newly released 0.2.3 version of the library.

**Comment by moham96** [comment]
@tkarabela, unfortunately, The problem is not fixed, as a matter of fact, I now get the exception even if I passed the style as a Unicode string.
Thank you for your great work

**Comment by tkarabela** [comment]
I'm sorry to hear that, @moham96. I've tested the change and seems to be working on my end (Ubuntu 17.10, Python 2.7.14):

```python
import pysubs2
import chardet

finput='en.srt'
foutput='en.ass'

# check pysubs2 version
print "using pysubs2 version", pysubs2.VERSION

# create dummy input data
with open(finput, "w") as fi:
    print >>fi, "1"
    print >>fi, "00:00:00,00 --> 00:01:00,00"
    print >>fi, "Hello world"

with open(finput,'rb') as fi:
    rawdata = fi.read()
    encoding = chardet.detect(rawdata)['encoding']
fi.close()

subs1 = pysubs2.load(finput)
top_style = pysubs2.SSAStyle()
top_style.alignment=8
subs1.styles['top-style'] = top_style
for line in subs1:
    line.style='top-style'
subs1.save(foutput,format_='ass')

# check output file
with open(foutput) as fo:
    print fo.read()
```

Output:

```
using pysubs2 version 0.2.3
[Script Info]
; Script generated by pysubs2
; https://pypi.python.org/pypi/pysubs2
WrapStyle: 0
ScaledBorderAndShadow: yes
Collisions: Normal
ScriptType: v4.00+

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,20.0,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100.0,100.0,0.0,0.0,1,2.0,2.0,2,10,10,10,1
Style: top-style,Arial,20.0,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100.0,100.0,0.0,0.0,1,2.0,2.0,8,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:01:00.00,top-style,,0,0,0,,Hello world
```

Can you send me your exact script and stack trace that is still throwing exception in pysubs2 v0.2.3?

**Comment by moham96** [comment]
@tkarabela  
It  is solved, I upgraded the library in the python3 site-packages and tested on the python2  :sweat_smile: 
It was a stupid mistake on my end.

Thank you very much for your help
