### ISSUE TITLE
Cannot read script info with out space after colon.

### ISSUE THREAD

**Issue by joshuaavalon** [tkarabela/pysubs2#14]
For example,

```
[Script Info]
Title:Ttitle
Original Script:Script
Synch Point:0
ScriptType:v4.00+
Collisions:Normal
PlayResX:640
PlayResY:360
Timer:100.0000
```

pysubs2 only has a empty dict in info.

**Comment by joshuaavalon** [comment]
I think the problem is 
https://github.com/tkarabela/pysubs2/blob/b04a8a7a1bafd5a8976f27df0ad8f01ba86080bc/pysubs2/substation.py#L187

Is there any reasons to use `": "` over `":"`?

**Comment by bergerspencer** [comment]
I have seen files in the wild with some (but not all) Script Info lines missing their spaces. Aegisub reads them fine. [ass-specs.doc](http://moodub.free.fr/video/ass-specs.doc) (link from [here](https://www.matroska.org/technical/specs/subtitles/ssa.html)) does not appear to contain an explicit requirement for a space after a line descriptor.
