### ISSUE TITLE
Drop Python 2, Support Python 3

### ISSUE THREAD

**Issue by erayerdin** [tkarabela/pysubs2#22]
Title says it all. I'm planning to provide PR for this, which will start from 3.4 exactly.

**Comment by tkarabela** [comment]
I'm not too hot on this. As Python 3 is already supported, what would be the benefit?

**Comment by erayerdin** [comment]
Actually, now I'm thinking about this, it might not be a great idea. While I was thinking about it, [Python 2 EOL](https://legacy.python.org/dev/peps/pep-0373/#id2) just came to my mind.

The only drawback I can think of is that further contribution to the codebase would require a significant care about compability between versions, which, actually, can be dealt via using `tox` and build matrix of Travis.

You can, if you wish to, close the issue.

**Comment by erayerdin** [comment]
Where did you get these stats?

Does it show which time period 2.7 downloads happened?

**Comment by hugovk** [comment]
I used this tool, which is getting the data from the PyPI stats stored in a Google BigQuery database:

https://github.com/hugovk/pypistats

Specifically, `pypistats python_minor --last-month pysubs2`, and those stats are for 1-30 September 2018.

**Comment by erayerdin** [comment]
Stats and tool are great. :+1: 

[Statistics](https://pypistats.org/packages/pysubs2) shows a small number of users in latest 30 days, as @hugovk provided, consists of 8.88% of users. This *is* a small number, still a bit significant though.

Again, this is the owner's, @tkarabela's decision to make. The important things to consider are:

i. Will this project be developed further?
ii. Or is it good enough in current state?

If the case is (i), then it is highly best to migrate to Python 3 since the newer versions of Python became almost incompatible with 2.7. If we do not migrate, then we will have to deal with compatibility between the latest version of Python we support and 2.7.

If the case is (ii), then we don't have to migrate. Any bug issues can be patched any time by owner, maintainers and contributors.

**Comment by tkarabela** [comment]
I have now seen the light :) And as of 11d8264be99ff7a1e7b353f44db02c39888b36ae, the library has been migrated to Python 3.7. I did general code cleanup and added type hints, which should make coding a better experience. This will be part of the next release; older Pythons are still supported by current version 0.2.4.
