### ISSUE TITLE
Subtitle File To Text is omitting subscripts

### ISSUE THREAD

**Issue by dorianherle** [tkarabela/pysubs2#26]
I am using pysub2 to read subtitle files. Here is a little example:

```

SIMPLE_FILE = """
1
00:00:00,000 --> 00:01:00,000
cette matrice-là <i>E<sub>t</sub>·…·E<sub>1</sub>A</i> possède une ligne

2
00:01:00,000 --> 00:02:00,000
there was a SubRip file
with two subtitles.
"""
with open("subtitles.srt", "w", encoding="utf-8") as fp:fp.write(SIMPLE_FILE)

import pysubs2
subs = pysubs2.load("subtitles.srt",format_= "srt")
subs[0].text
```

As a result I get:

> cette matrice-là {\i1}Et·…·E1A{\i0} possède une ligne

As you can see the <i> symbols where successfully recognized, however the subscript <sub> was omitted. 

I am wondering, if there is a method to also make sure that the subscript is there ?

**Comment by tkarabela** [comment]
This works as of pysubs2 v1.0.0, please use `pysubs2.load(..., keep_unknown_html_tags=True)`:

```python
SIMPLE_FILE = """
1
00:00:00,000 --> 00:01:00,000
cette matrice-là <i>E<sub>t</sub>·…·E<sub>1</sub>A</i> possède une ligne

"""

with open("subtitles.srt", "w", encoding="utf-8") as fp:
    fp.write(SIMPLE_FILE)

import pysubs2
subs = pysubs2.load("subtitles.srt", keep_unknown_html_tags=True)
print(subs[0].text)  # cette matrice-là {\i1}E<sub>t</sub>·…·E<sub>1</sub>A{\i0} possède une ligne
```

It also works as intended when you save the subtitles again as SRT (HTML tags are preserved).
