### ISSUE TITLE
webvtt fragments

### ISSUE THREAD

**Issue by X-C0DE** [tkarabela/pysubs2#30]
how do i join fragments of a subtitle in webvtt and convert everything to srt?

ex: I have a folder with 4 subtitle files in webvtt and I need to unite them and convert to a single srt file

subtitle_V1-0.webvtt
subtitle_V1-1.webvtt
subtitle_V1-2.webvtt
subtitle_V1-3.webvtt

convert to

subtitle.srt

**Comment by tkarabela** [comment]
While `pysubs2` has no particular support for WebVTT format at this time, the format is sufficiently similar to SRT that in simple cases, `pysubs2` will read it just fine. If you just want to collect subtitles from multiple files without any retiming, that would be:

```python
import pysubs2


input_files = [
    "subtitle_V1-0.webvtt",
    "subtitle_V1-1.webvtt",
    "subtitle_V1-2.webvtt",
    "subtitle_V1-3.webvtt",
]

output_subs = pysubs2.SSAFile()

for file in input_files:
    subs = pysubs2.load(file)
    output_subs.events.extend(subs.events)

output_subs.save("subtitle.srt")
```

**Comment by X-C0DE** [comment]
> While `pysubs2` has no particular support for WebVTT format at this time, the format is sufficiently similar to SRT that in simple cases, `pysubs2` will read it just fine. If you just want to collect subtitles from multiple files without any retiming, that would be:
> 
> ```python
> import pysubs2
> 
> 
> input_files = [
>     "subtitle_V1-0.webvtt",
>     "subtitle_V1-1.webvtt",
>     "subtitle_V1-2.webvtt",
>     "subtitle_V1-3.webvtt",
> ]
> 
> output_subs = pysubs2.SSAFile()
> 
> for file in input_files:
>     subs = pysubs2.load(file)
>     output_subs.events.extend(subs.events)
> 
> output_subs.save("subtitle.srt")
> ```

Hi
Thanks a lot for the help
but there is something that didn't work well

I tested this code with 2 parts of subtitles (subtitles_V1-0.webvtt and subtitles_V1-1.webvtt), and in the final file instead of having the first complete subtitle and as a continuation of the second, I had the opposite

![photo_2020-02-05_11-08-58](https://user-images.githubusercontent.com/56088454/73849034-f627dd00-4807-11ea-889a-2e9343fed0fd.jpg)

this first line should be at the end of the file

**Comment by X-C0DE** [comment]
> While `pysubs2` has no particular support for WebVTT format at this time, the format is sufficiently similar to SRT that in simple cases, `pysubs2` will read it just fine. If you just want to collect subtitles from multiple files without any retiming, that would be:
> 
> ```python
> import pysubs2
> 
> 
> input_files = [
>     "subtitle_V1-0.webvtt",
>     "subtitle_V1-1.webvtt",
>     "subtitle_V1-2.webvtt",
>     "subtitle_V1-3.webvtt",
> ]
> 
> output_subs = pysubs2.SSAFile()
> 
> for file in input_files:
>     subs = pysubs2.load(file)
>     output_subs.events.extend(subs.events)
> 
> output_subs.save("subtitle.srt")
> ```

Thanks a lote
This way works for me

**Comment by X-C0DE** [comment]
Hey
I Tryied the same code for vtt subtitles and it not works. How can I do this to works with vtt files?

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.6/site-packages/pysubs2/ssafile.py", line 92, in load
    return cls.from_file(fp, format_, fps=fps, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pysubs2/ssafile.py", line 145, in from_file
    format_ = autodetect_format(fragment)
  File "/usr/local/lib/python3.6/site-packages/pysubs2/formats.py", line 62, in autodetect_format
    raise FormatAutodetectionError("No suitable formats")
pysubs2.exceptions.FormatAutodetectionError: No suitable formats
```

**Comment by tkarabela** [comment]
You can try to force the input format to get around autodetection:

```py
subs = pysubs2.load("test.vtt", format_="srt")
subs.save("test.srt")
```

However, WebVTT is fundamentally a different format than SRT, so re-using SRT parser to load such files is a "hack". It may be necessary to implement proper WebVTT parser to read more complex files.

**Comment by X-C0DE** [comment]
hmm
it not works correctly. sad life

**Comment by X-C0DE** [comment]
is it possible for me to use pysubs2 only to concatenate subtitles in srt?
['sub_1.srt', 'sub_2.srt', 'sub_3.srt']  >>> subtitle.srt

**Comment by tkarabela** [comment]
Can you share the `.vtt` file which could not be loaded by `pysubs2`? I can have a look at it.

As for merging SRT files, yes you can do that:

```py
import pysubs2

input_files = [
    "sub_1.srt",
    "sub_2.srt",
    "sub_3.srt",
]

output_subs = pysubs2.SSAFile()

for file in input_files:
    subs = pysubs2.load(file)
    output_subs.events.extend(subs.events)

output_subs.save("subtitle.srt")
```

**Comment by X-C0DE** [comment]
> Can you share the `.vtt` file which could not be loaded by `pysubs2`? I can have a look at it.
> 
> As for merging SRT files, yes you can do that:
> 
> ```python
> import pysubs2
> 
> input_files = [
>     "sub_1.srt",
>     "sub_2.srt",
>     "sub_3.srt",
> ]
> 
> output_subs = pysubs2.SSAFile()
> 
> for file in input_files:
>     subs = pysubs2.load(file)
>     output_subs.events.extend(subs.events)
> 
> output_subs.save("subtitle.srt")
> ```

VTT files:
[vtt_files.zip](https://github.com/tkarabela/pysubs2/files/4634879/vtt_files.zip)
For concatenate srt files i already tryied to use this, but it not works.

**Comment by tkarabela** [comment]
I have added explicit support for VTT files into the library and successfully merged your testing files with this script:

```py
import pysubs2
import glob

input_files = glob.glob("SUB_*.vtt")

output_subs = pysubs2.SSAFile()

for file in input_files:
    subs = pysubs2.load(file)
    output_subs.events.extend(subs.events)

output_subs.save("subtitle.srt")
```

I will be releasing a new version of `pysubs2` shortly. Relevant changes are in commit 29629fd2167e586c99b4694c21e8c0e21b9da9c5.
