### ISSUE TITLE
Converting TMP into SubRip results in overlapped cues

### ISSUE THREAD

**Issue by baxtree** [tkarabela/pysubs2#35]
Hi,

When trying to convert a TMP subtitle into to SubRip, I found the end time generated by pysubs2 for a subtitle cue is after the start time of the next one. E.g,

TMP                              | SubRip
00:00:12:I ...                 | 00:00:12,000 --> 00:00:15,113 
00:00:14:observing ... | 00:00:14,000 --> 00:00:18,319 
00:00:18:and ...           | 00:00:18,000 --> 00:00:22,252
00:00:22:You ...           | 00:00:22,000 --> 00:00:25,448

Looking closer, found the end time is calculated by https://github.com/tkarabela/pysubs2/blob/fc534732fc58af2bce78d14b56614b2df544f150/pysubs2/tmp.py#L50-L51

Was that intentional? It seems to make more sense to make the end time not go beyond the start time of the next cue during the calculation.

**Comment by tkarabela** [comment]
Thanks for the bug report! :) Indeed, this shouldn't be happening. I missed this when reviewing the pull request which added TMP format. It should be fixed now.

**Comment by baxtree** [comment]
Oh cool! Thanks for sharing this library.
