### ISSUE TITLE
ass to srt issue

### ISSUE THREAD

**Issue by josscmorera** [tkarabela/pysubs2#37]
Hello, I found that ass transcoding to .srt fails on deleting/bypassing karakoke subs and drawings  {\an5\pos(655.758,142.500) /blur

I have attached the transcoded file and images on how it looks on video
[Archive.zip](https://github.com/tkarabela/pysubs2/files/5978636/Archive.zip)

**Comment by tkarabela** [comment]
Hi, I've replicated your result with current release (1.0.0, 7159a89b8c253c8f154cca257f56a75bb2228399):

```sh
python -m pysubs2 --to srt original.ass
```
and I got the same output as you did (`5.srt`).

- In the original ASS file, there are three kinds of lines: (1), (2) and (3), where only (1) should ideally be written to the SRT file.
- (2) is being skipped in the current version, so that's good.
- As for (3), I'm not sure how pysubs should tell the difference between (1) and (3)? Both are dialogue lines with some override tags.

---

#### (1) Regular dialogue, possibly with override tags
These are handled OK, tags are stripped.
```
Dialogue: 0,0:24:06.04,0:24:11.01,Signs,,0,0,0,,{\fnAdobe Garamond Pro\b0\bord4\blur4\c&H060706&\3c&H060706&\fs73\pos(960,654.143)}Warrior
```
```
2635
00:24:06,040 --> 00:24:11,010
Warrior
```

#### (2) ASS drawing tags, {\p}
These are handled OK, skipped for SRT output (thanks to https://github.com/tkarabela/pysubs2/pull/31).
```
Dialogue: 13,0:00:20.65,0:00:20.85,OP-E,,0,0,0,,{\an5\pos(926.695,148.500)\fad(50,50)\bord0\1c&HFFFFFF&\blur2\alpha&H53&\p1}m 0 5 b 0 5 0 0 5 0 5 0 10 0 10 5 10 5 10 10 5 10 5 10 0 10 0 5
```
`(nothing)`

#### (3) Rendered karaoke lines
These are written to the output SRT, which is unfortunate.
```
Dialogue: 10,0:00:07.24,0:00:10.03,OP-E,,0,0,0,,{\an5\pos(655.758,142.500)\1c&H4E4AFB&\3c&H4E4AFB&\blur2.4\bord2.5\fad(300,300)}I
```
```
1
00:00:07,240 --> 00:00:10,030
I
```

**Comment by josscmorera** [comment]
would it be possible to force-delete the lines that gives out only 1 letter?

**Comment by tkarabela** [comment]
> 
> 
> would it be possible to force-delete the lines that gives out only 1 letter?

Sure :) I'd make it optional though, so that no visible subtitles are deleted by default. Would adding a new commandline parameter, something like `--clean`, work for you? Ie.:

```sh
python -m pysubs2 --to srt --clean original.ass
```

**Comment by josscmorera** [comment]
that would be really awesome :)

**Comment by tkarabela** [comment]
I've released version 1.1.0 of the library, which includes `--clean` :) You can test it and then we can close the issue.

**Comment by josscmorera** [comment]
I just tested it and works amazingly, while testing it I found this:
```
00:25:35,120 --> 00:25:43,810
æ¶™ãªã‚“ã¦è¦‹ã›ãªã„ã‚“ã
```

Not sure if this could be related but let me know if yes or not to close this issue 
Thank you 
[Archive 21.zip](https://github.com/tkarabela/pysubs2/files/6053521/Archive.21.zip)

**Comment by tkarabela** [comment]
Oh, I see. That's not related to `--clean`, it's the character encoding. Please try:

```sh
python -m pysubs2 --to srt --clean --input-enc utf8 original.ass
```

That should fix the problem. I will look into this if it could be handled better in the CLI for some future release.

**Comment by josscmorera** [comment]
Works great thank a lot, all good for now so I proceed to close this issue. :)

**Comment by toprak** [comment]
@tkarabela it does not work on me as expected on library mode.
```def extract_and_convert_subs(mkv_file, sub_index, untranslated_path):
    base_file = mkv_file.with_suffix('')
    extracted_sub_file = untranslated_path / f"{base_file.name}.ass"

    # Extract the subtitle in its original format
    subprocess.run(['ffmpeg', '-hide_banner', '-loglevel', 'error', '-i', str(mkv_file), '-map', f'0:s:{sub_index}', f'{extracted_sub_file}'], check=True)

    # Check if the subtitle format is ASS and convert it to SRT if necessary
    with open(extracted_sub_file, 'r', encoding='utf-8') as f:
        first_line = f.readline()

    if first_line.startswith('[Script Info]'):
        ass_subs = pysubs2.load(str(extracted_sub_file), encoding="utf-8")
        srt_file = untranslated_path / f"{base_file.name}.srt"
        ass_subs.remove_miscellaneous_events()
        ass_subs.save(str(srt_file), format_='srt', encoding="utf-8")
        os.remove(str(extracted_sub_file))
    else:
        extracted_sub_file.rename(untranslated_path / f"{base_file.name}.srt")
```
it adds karaokes that are only 2 letter
