### ISSUE TITLE
CLI, default to UTF-8

### ISSUE THREAD

**Issue by tkarabela** [tkarabela/pysubs2#38]
Consider making `--input-enc utf8` default, with some fallback. It already is default in the Python API, however as of 1.1.0 we're defaulting to ISO-8859-1 in the CLI, which obviously breaks on some inputs. See https://github.com/tkarabela/pysubs2/issues/37#issuecomment-786983269.

**Comment by gormih** [comment]
https://github.com/tkarabela/pysubs2/blob/10c3bb8d5bcb9ab51609a0bdde5f892da9891952/pysubs2/ssafile.py#L54

**Comment by tkarabela** [comment]
@gormih, you are right that `SSAFile` interface already defaults to UTF-8. This issue is referring to the commandline interface, ie.

```
python -m pysubs2 ...
```

https://github.com/tkarabela/pysubs2/blob/10c3bb8d5bcb9ab51609a0bdde5f892da9891952/pysubs2/cli.py#L72-L74
