### ISSUE TITLE
html tags --clean

### ISSUE THREAD

**Issue by josscmorera** [tkarabela/pysubs2#39]
Would be possible that under the --clean command or a new one will it delete the html tags on the subtitles for example

```
<i>They're dying in vain!</i>

to 

They're dying in vain!
```

Thanks in advance

**Comment by tkarabela** [comment]
Yes, it could:

- remove all override tags `{...}` from subtitles
- for non-SubStation output, do not convert SubStation styles to override tags for given format.

That should keep the output "clean" from any usual tags (unrecognized HTML or other tags would still be passed through).

**Comment by josscmorera** [comment]
thats amazing!! so it would also be possible to add such feature to the command line interface? 😅😅

**Comment by tkarabela** [comment]
Sure, it would be under the `--clean` parameter.

**Comment by tkarabela** [comment]
This is now part of 1.2.0 release :)
