### ISSUE TITLE
English Language Only subs

### ISSUE THREAD

**Issue by josscmorera** [tkarabela/pysubs2#40]
Hi,

Last time there was an issue on the subs adding Japanese / Chinese subs to the final .srt was recommended to use the UTF-8 but it still gives out some Japanese characters like on the files attached
sample: 

```
13
00:24:18,670 --> 00:24:22,570
呼びかけた声かき消されて
```

[Archive 2s2.zip](https://github.com/tkarabela/pysubs2/files/6095531/Archive.2s2.zip)

**Comment by tkarabela** [comment]
Well... yes? :) The purpose of specifying encoding is to make sure that existing text doesn't get corrupted, ie. Japanese characters from input are still the same characters in output, and not some random characters or questionmarks. It's not meant to strip text based on its script.

**Comment by josscmorera** [comment]
> Well... yes? :) The purpose of specifying encoding is to make sure that existing text doesn't get corrupted, ie. Japanese characters from input are still the same characters in output, and not some random characters or questionmarks. It's not meant to strip text based on its script.

ohhhh it make sense now but will there be anyway to strip non english texts or it would be impossible?

**Comment by tkarabela** [comment]
Proper way to do this would be to detect language for each subtitle. As a quick approximation, you can look up Unicode parameters of the individual characters and reject based on that, like this:

```py
import pysubs2
import unicodedata

def is_non_latin(text: str):
    # https://www.unicode.org/reports/tr44/#General_Category_Values
    return "Lo" in map(unicodedata.category, text)  # "Letter - other" category (kanji, etc.)

subs = pysubs2.load("...")
subs.events = [line for line in subs if not is_non_latin(line.plaintext)]
subs.save("...")
```

**Comment by tkarabela** [comment]
Closing this issue, a simple workaround is available https://github.com/tkarabela/pysubs2/issues/40#issuecomment-791992116 and I feel that proper addressing of language handling is out of scope of this library.

**Comment by akashAD98** [comment]
@tkarabela so other language .srt is not supporting? i have 20 min of subtitle, how should i apply unicodedata to each subtitle?

**Comment by tkarabela** [comment]
> @tkarabela so other language .srt is not supporting? i have 20 min of subtitle, how should i apply unicodedata to each subtitle?

Hi @akashAD98, the SRT subtitle format as well as this library doesn't really care about language of the subtitles: as far as `pysubs2` is concerned, subtitles are just Unicode text; with SRT it depends on the character encoding of the file (which is hopefully also Unicode, eg. UTF-8). You can work with subtitles in whichever language you want, just be sure to correctly specify `pysubs2.load(encoding=...)` or `subs.save(encoding=...)` if you're not using UTF-8 (which is the default).

This GitHub issue is about removing individual subtitles based on what language is the text of that subtitle, which requires some sort of language detection. I'm not sure that it's relevant to you, or what is your particular issue?
