### ISSUE TITLE
Embedded Fonts

### ISSUE THREAD

**Issue by sethazazel** [tkarabela/pysubs2#41]
Hi, i think pysub2 doesn't copy embedded fonts to new subtitle file. Can you add this feature please? 
[https://github.com/smacke/ffsubsync/issues/126](https://github.com/smacke/ffsubsync/issues/126)

**Comment by tkarabela** [comment]
Sure, I will add it in the next release :)

(It's a bit funny, as I remember that my original `pysubs` library from before 2014 handled this, I must have removed that for `pysubs2` as I thought nobody was using it.)

**Comment by sethazazel** [comment]
Thank you :)

**Comment by tkarabela** [comment]
It's here in pysubs2 version 1.2.0 :)
