### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by guhailong18** [tkarabela/pysubs2#42]
I tried a few things, but they all failed,

**Comment by tkarabela** [comment]
Hi, it appears that the subtitle file you're trying to read is not in UTF-8 encoding. In this case, it's needed to tell pysubs2 what encoding you have:

**API**
```
import pysubs2
subs = pysubs2.load("subtitles.srt", encoding="YOUR-ENCODING-HERE")
```

**CLI**
```
python -m pysubs2 --input-enc YOUR-ENCODING-HERE subtitles.srt
```

You can find list of all encodings that Python supports here: https://docs.python.org/3/library/codecs.html#standard-encodings

**Comment by guhailong18** [comment]
> 嗨，您似乎要阅读的字幕文件不是采用UTF-8编码。在这种情况下，需要告诉pysubs2您使用哪种编码：
> 
> **原料药**
> 
> ```
> import pysubs2
> subs = pysubs2.load("subtitles.srt", encoding="YOUR-ENCODING-HERE")
> ```
> 
> **命令行界面**
> 
> ```
> python -m pysubs2 --input-enc YOUR-ENCODING-HERE subtitles.srt
> ```
> 
> 您可以在此处找到Python支持的所有编码的列表：[https](https://docs.python.org/3/library/codecs.html#standard-encodings) : [//docs.python.org/3/library/codecs.html#standard-encodings](https://docs.python.org/3/library/codecs.html#standard-encodings)

Thanks,I use [chardet](https://github.com/chardet/chardet) auto-detect file encoding format.
The problem was solved successfully

**Comment by mrfragger** [comment]
Just a note I transcribed subs and always never specified utf-8 and many languages worked.  However with Hindi I had to specify --input-enc latin-1 and to use pysubs2 to shift sub timings and it magically worked. chardetect said 0.99 probability it was utf-8 so go figure.
