### ISSUE TITLE
how to set ass style with a dict

### ISSUE THREAD

**Issue by Yuelioi** [tkarabela/pysubs2#44]
Now , when i set ass stlye :
import pysubs2
assfile = pysubs2.SSAFile()
assfile.styles['sytle1'] = pysubs2.SSAStyle(fontname = 'xxx', fontsize = 20)

can i use a dict to work with it, just like
style_dict = {
  'fontname':'xxx',
  'fontsize':20
}

assfile.styles['sytle1'] = pysubs2.SSAStyle(style_dict)

**Comment by tkarabela** [comment]
This should work :)

```py
style_dict = {
    'fontname': 'xxx',
    'fontsize': 20
}

assfile.styles['style1'] = pysubs2.SSAStyle(**style_dict)
```
