### ISSUE TITLE
Options to keep the ASS positioning tag in srt files

### ISSUE THREAD

**Issue by toroConverter** [tkarabela/pysubs2#48]
Hi @tkarabela I am using your library to do some preprocessing on some SRT files and I noticed that your code remove the ASS positioning tag (e.g. {\an7}).
Is it possibile to add a parameter to save function to keep them also in the output file?

**Comment by toroConverter** [comment]
Thanks for your fantastic work ;)

**Comment by tkarabela** [comment]
Hi @toroConverter it's in version 1.4.0 of the library:

```
subs.to_file("subs.srt", keep_ssa_tags=True)
```

(For completeness, it's also available as ``--srt-keep-ssa-tags`` from the CLI.)

**Comment by toroConverter** [comment]
Thanks a lot!

**Comment by toroConverter** [comment]
@tkarabela I think that you forgot to replace the text formatting tags.
Example of output save > _{\i1}Blah blah blah{\i0}_

**Comment by tkarabela** [comment]
So you would like to have *both* HTML tags and any ASS tags not convertible to HTML kept as-is, like this?

```
{\an7}Example <i>text</i>.
```

**Comment by toroConverter** [comment]
Yes, if it is possibile.
Very often I manage srt files that have both

**Comment by tkarabela** [comment]
Hi @toroConverter , hopefully new version 1.4.1 solves your problem :) I've added parser option to keep all HTML tags, so if you use both options together it should keep everything.

```python
import pysubs2
subs = pysubs2.load("test.srt", keep_html_tags=True)
subs.save("test-output.srt", keep_ssa_tags=True)
```

**Comment by toroConverter** [comment]
@tkarabela it is working well! Thanks a lot for your effort ;)
