### ISSUE TITLE
Add typehints

### ISSUE THREAD

**Issue by tkarabela** [tkarabela/pysubs2#5]
Write typehints as per PEP 484 for better programming experience.

**Comment by erayerdin** [comment]
This might raise a problem since type hinting has been supported from the version 3.5.

**Comment by tkarabela** [comment]
Yes, I was thinking about the comment syntax, which works decently in my experience, if it is a bit awkward to write :) It's much better than nothing, even though the type checker/type inference tends to give up with more complex code.

**Comment by tkarabela** [comment]
Implemented in 11d8264be99ff7a1e7b353f44db02c39888b36ae.
