### ISSUE TITLE
Support for Graphics section

### ISSUE THREAD

**Issue by PalmtopTiger** [tkarabela/pysubs2#59]
Could you consider adding support for Graphics section, please? It is lost after conversion.
Aegisub is able to add files to this section. And, if I remember correctly, VSFilterMod can render images from it.

The format of the Graphics section is almost the same as that of Fonts. Just "fontname" becomes "filename".
[Specs](http://moodub.free.fr/video/ass-specs.doc)
[sample.zip](https://github.com/tkarabela/pysubs2/files/10037612/sample.zip)

**Comment by tkarabela** [comment]
Sure, I'll look into it :)

**Comment by tkarabela** [comment]
Implemented in 1.6.0. version of the library, thanks again for the request and test data :)

**Comment by PalmtopTiger** [comment]
Thank you!
