### ISSUE TITLE
Is there a way to add braces to the SRT file?

### ISSUE THREAD

**Issue by FlippFuzz** [tkarabela/pysubs2#70]
Sample code:
```
import pysubs2

subs = pysubs2.SSAFile()
subs.append(pysubs2.SSAEvent(start=0, end=1, text='Start{sometext}End'))
subs.save('braces.srt')
```

Output:
```
1
00:00:00,000 --> 00:00:00,001
Start\End
```

I'm hoping to see `Start{sometext}End` as the actual text for this subtitle.

**Comment by FlippFuzz** [comment]
If it helps, the use case here is that I want to dump some JSON based metadata into the SRT file.
Was going to hide it in the first millisecond of the SRT file.

**Comment by tkarabela** [comment]
Hi @FlippFuzz, you can do it like this:

```python
import pysubs2

subs = pysubs2.SSAFile()
subs.append(pysubs2.SSAEvent(start=0, end=1, text='Start{sometext}End'))
subs.save('braces.srt', keep_ssa_tags=True)
```

This will bypass processing of `{...}` when writing to SRT. Note that in the current implementation, strings `\h`, `\n` and `\N` (ie. backslash followed by h, n or N) will be replaced by a space and newline character respectively, regardless of the "keep_ssa_tags" option. It's possible that this could mess up some strings inside your JSON data - I can update the code to never do any substitutions when "keep_ssa_tags" is True, to be on the safe side - what do you think? :)

**Comment by FlippFuzz** [comment]
`subs.save('braces.srt', keep_ssa_tags=True)` works for my use case. I don't have those characters. 
Thank you!

Perhaps, it will be nice to have a flag on the SSAEvent itself instead of the entire SSAFile so that SSA tags are only ignored for one specific SSAEvent instead of everything.
Or maybe have escape characters for `{` and `}`?
But these are just some ideas and are at most low priority feature enhancements. I don't need them right now.

Thanks again.

**Comment by tkarabela** [comment]
Glad it helped :) If you encounter any particular limitations, feel free to open another issue and we'll sort it out.
