### ISSUE TITLE
add format sami = smi

### ISSUE THREAD

**Issue by milahu** [tkarabela/pysubs2#80]
sami is a rarely-used subtitles format, which looks like broken html (unclosed tags)

https://en.wikipedia.org/wiki/SAMI

https://github.com/LinearAlpha/smi2ass/blob/main/smi2ass.py - hacky... fighting the html parser

https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParserSami.cpp

https://github.com/videolan/vlc/blob/master/modules/demux/subtitle.c#L1380 - static int ParseSami

i would implement this as an ~~xml~~ [html stream parser](https://docs.python.org/3/library/html.parser.html), to handle all the unclosed tags
and because we dont need the html dom - we build our own "document"

**Comment by tkarabela** [comment]
Implemented in 1.8.0.
