### ISSUE TITLE
Suggestion: display the help message when pysubs2 is run from CLI without any arguments

### ISSUE THREAD

**Issue by Northurland** [tkarabela/pysubs2#81]
Currently, if you type `pysubs2` directly into the command line and push enter, the module would load - but do nothing, and not automatically exiting. It would be good if a help message is printed and then the CLI tool exits automatically in this case.

I have the intention to contribute code for this feature, if that is permitted.

**Comment by tkarabela** [comment]
Hi @Northurland, if you'd like to send a pull request, you're welcome to do so :)

**Comment by Northurland** [comment]
@tkarabela 

A pull request is sent.
Thank you!

#82
